// Code generated by MockGen. DO NOT EDIT.
// Source: leave_service.go
//
// Generated by this command:
//
//	mockgen -source=leave_service.go -destination=../mock/mock_leave_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/nanato-okajima/attendance_management/internal/entity"
	service "github.com/nanato-okajima/attendance_management/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockLeaveService is a mock of LeaveService interface.
type MockLeaveService struct {
	ctrl     *gomock.Controller
	recorder *MockLeaveServiceMockRecorder
	isgomock struct{}
}

// MockLeaveServiceMockRecorder is the mock recorder for MockLeaveService.
type MockLeaveServiceMockRecorder struct {
	mock *MockLeaveService
}

// NewMockLeaveService creates a new mock instance.
func NewMockLeaveService(ctrl *gomock.Controller) *MockLeaveService {
	mock := &MockLeaveService{ctrl: ctrl}
	mock.recorder = &MockLeaveServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeaveService) EXPECT() *MockLeaveServiceMockRecorder {
	return m.recorder
}

// CreateLeaveRequest mocks base method.
func (m *MockLeaveService) CreateLeaveRequest(ctx context.Context, req *service.CreateLeaveRequestInput) (*entity.LeaveRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLeaveRequest", ctx, req)
	ret0, _ := ret[0].(*entity.LeaveRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLeaveRequest indicates an expected call of CreateLeaveRequest.
func (mr *MockLeaveServiceMockRecorder) CreateLeaveRequest(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLeaveRequest", reflect.TypeOf((*MockLeaveService)(nil).CreateLeaveRequest), ctx, req)
}

// GetLeaveRequestByID mocks base method.
func (m *MockLeaveService) GetLeaveRequestByID(ctx context.Context, id uint) (*entity.LeaveRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLeaveRequestByID", ctx, id)
	ret0, _ := ret[0].(*entity.LeaveRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLeaveRequestByID indicates an expected call of GetLeaveRequestByID.
func (mr *MockLeaveServiceMockRecorder) GetLeaveRequestByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLeaveRequestByID", reflect.TypeOf((*MockLeaveService)(nil).GetLeaveRequestByID), ctx, id)
}

// GetLeaveRequests mocks base method.
func (m *MockLeaveService) GetLeaveRequests(ctx context.Context, employeeNumber int, status *entity.ApprovalStatus) ([]*entity.LeaveRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLeaveRequests", ctx, employeeNumber, status)
	ret0, _ := ret[0].([]*entity.LeaveRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLeaveRequests indicates an expected call of GetLeaveRequests.
func (mr *MockLeaveServiceMockRecorder) GetLeaveRequests(ctx, employeeNumber, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLeaveRequests", reflect.TypeOf((*MockLeaveService)(nil).GetLeaveRequests), ctx, employeeNumber, status)
}

// GetRemainingPaidLeaveDays mocks base method.
func (m *MockLeaveService) GetRemainingPaidLeaveDays(ctx context.Context, employeeNumber int) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemainingPaidLeaveDays", ctx, employeeNumber)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRemainingPaidLeaveDays indicates an expected call of GetRemainingPaidLeaveDays.
func (mr *MockLeaveServiceMockRecorder) GetRemainingPaidLeaveDays(ctx, employeeNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemainingPaidLeaveDays", reflect.TypeOf((*MockLeaveService)(nil).GetRemainingPaidLeaveDays), ctx, employeeNumber)
}
