// Code generated by MockGen. DO NOT EDIT.
// Source: correction_repository.go
//
// Generated by this command:
//
//	mockgen -source=correction_repository.go -destination=../../mock/mock_correction_repository.go -package=mock -mock_names CorrectionRepository=MockCorrectionRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/nanato-okajima/attendance_management/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockCorrectionRepository is a mock of CorrectionRepository interface.
type MockCorrectionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCorrectionRepositoryMockRecorder
	isgomock struct{}
}

// MockCorrectionRepositoryMockRecorder is the mock recorder for MockCorrectionRepository.
type MockCorrectionRepositoryMockRecorder struct {
	mock *MockCorrectionRepository
}

// NewMockCorrectionRepository creates a new mock instance.
func NewMockCorrectionRepository(ctrl *gomock.Controller) *MockCorrectionRepository {
	mock := &MockCorrectionRepository{ctrl: ctrl}
	mock.recorder = &MockCorrectionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCorrectionRepository) EXPECT() *MockCorrectionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCorrectionRepository) Create(ctx context.Context, correction *entity.AttendanceCorrection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, correction)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCorrectionRepositoryMockRecorder) Create(ctx, correction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCorrectionRepository)(nil).Create), ctx, correction)
}

// FindByEmployeeNumber mocks base method.
func (m *MockCorrectionRepository) FindByEmployeeNumber(ctx context.Context, employeeNumber int, status *entity.ApprovalStatus) ([]*entity.AttendanceCorrection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmployeeNumber", ctx, employeeNumber, status)
	ret0, _ := ret[0].([]*entity.AttendanceCorrection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmployeeNumber indicates an expected call of FindByEmployeeNumber.
func (mr *MockCorrectionRepositoryMockRecorder) FindByEmployeeNumber(ctx, employeeNumber, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmployeeNumber", reflect.TypeOf((*MockCorrectionRepository)(nil).FindByEmployeeNumber), ctx, employeeNumber, status)
}

// FindByID mocks base method.
func (m *MockCorrectionRepository) FindByID(ctx context.Context, id uint) (*entity.AttendanceCorrection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.AttendanceCorrection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCorrectionRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCorrectionRepository)(nil).FindByID), ctx, id)
}

// FindPendingApprovals mocks base method.
func (m *MockCorrectionRepository) FindPendingApprovals(ctx context.Context) ([]*entity.AttendanceCorrection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPendingApprovals", ctx)
	ret0, _ := ret[0].([]*entity.AttendanceCorrection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPendingApprovals indicates an expected call of FindPendingApprovals.
func (mr *MockCorrectionRepositoryMockRecorder) FindPendingApprovals(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPendingApprovals", reflect.TypeOf((*MockCorrectionRepository)(nil).FindPendingApprovals), ctx)
}

// Update mocks base method.
func (m *MockCorrectionRepository) Update(ctx context.Context, correction *entity.AttendanceCorrection) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, correction)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCorrectionRepositoryMockRecorder) Update(ctx, correction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCorrectionRepository)(nil).Update), ctx, correction)
}
