// Code generated by MockGen. DO NOT EDIT.
// Source: approval_service.go
//
// Generated by this command:
//
//	mockgen -source=approval_service.go -destination=../mock/mock_approval_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/nanato-okajima/attendance_management/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockApprovalService is a mock of ApprovalService interface.
type MockApprovalService struct {
	ctrl     *gomock.Controller
	recorder *MockApprovalServiceMockRecorder
	isgomock struct{}
}

// MockApprovalServiceMockRecorder is the mock recorder for MockApprovalService.
type MockApprovalServiceMockRecorder struct {
	mock *MockApprovalService
}

// NewMockApprovalService creates a new mock instance.
func NewMockApprovalService(ctrl *gomock.Controller) *MockApprovalService {
	mock := &MockApprovalService{ctrl: ctrl}
	mock.recorder = &MockApprovalServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApprovalService) EXPECT() *MockApprovalServiceMockRecorder {
	return m.recorder
}

// ApproveLeaveRequest mocks base method.
func (m *MockApprovalService) ApproveLeaveRequest(ctx context.Context, id uint, approverID int, comment string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveLeaveRequest", ctx, id, approverID, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveLeaveRequest indicates an expected call of ApproveLeaveRequest.
func (mr *MockApprovalServiceMockRecorder) ApproveLeaveRequest(ctx, id, approverID, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveLeaveRequest", reflect.TypeOf((*MockApprovalService)(nil).ApproveLeaveRequest), ctx, id, approverID, comment)
}

// GetPendingApprovals mocks base method.
func (m *MockApprovalService) GetPendingApprovals(ctx context.Context) ([]*entity.LeaveRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingApprovals", ctx)
	ret0, _ := ret[0].([]*entity.LeaveRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingApprovals indicates an expected call of GetPendingApprovals.
func (mr *MockApprovalServiceMockRecorder) GetPendingApprovals(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingApprovals", reflect.TypeOf((*MockApprovalService)(nil).GetPendingApprovals), ctx)
}

// RejectLeaveRequest mocks base method.
func (m *MockApprovalService) RejectLeaveRequest(ctx context.Context, id uint, approverID int, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectLeaveRequest", ctx, id, approverID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectLeaveRequest indicates an expected call of RejectLeaveRequest.
func (mr *MockApprovalServiceMockRecorder) RejectLeaveRequest(ctx, id, approverID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectLeaveRequest", reflect.TypeOf((*MockApprovalService)(nil).RejectLeaveRequest), ctx, id, approverID, reason)
}
