// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=../../mock/mock_attendance_repository.go -package=mock -mock_names Repository=MockAttendanceRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	time "time"

	entity "github.com/nanato-okajima/attendance_management/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAttendanceRepository is a mock of Repository interface.
type MockAttendanceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAttendanceRepositoryMockRecorder
	isgomock struct{}
}

// MockAttendanceRepositoryMockRecorder is the mock recorder for MockAttendanceRepository.
type MockAttendanceRepositoryMockRecorder struct {
	mock *MockAttendanceRepository
}

// NewMockAttendanceRepository creates a new mock instance.
func NewMockAttendanceRepository(ctrl *gomock.Controller) *MockAttendanceRepository {
	mock := &MockAttendanceRepository{ctrl: ctrl}
	mock.recorder = &MockAttendanceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttendanceRepository) EXPECT() *MockAttendanceRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAttendanceRepository) Create(attendance *entity.Attendance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", attendance)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAttendanceRepositoryMockRecorder) Create(attendance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAttendanceRepository)(nil).Create), attendance)
}

// FindByEmployeeAndDate mocks base method.
func (m *MockAttendanceRepository) FindByEmployeeAndDate(employeeID int, date time.Time) (*entity.Attendance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmployeeAndDate", employeeID, date)
	ret0, _ := ret[0].(*entity.Attendance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmployeeAndDate indicates an expected call of FindByEmployeeAndDate.
func (mr *MockAttendanceRepositoryMockRecorder) FindByEmployeeAndDate(employeeID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmployeeAndDate", reflect.TypeOf((*MockAttendanceRepository)(nil).FindByEmployeeAndDate), employeeID, date)
}

// FindByEmployeeAndDateRange mocks base method.
func (m *MockAttendanceRepository) FindByEmployeeAndDateRange(employeeID int, startDate, endDate time.Time) ([]entity.Attendance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmployeeAndDateRange", employeeID, startDate, endDate)
	ret0, _ := ret[0].([]entity.Attendance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmployeeAndDateRange indicates an expected call of FindByEmployeeAndDateRange.
func (mr *MockAttendanceRepositoryMockRecorder) FindByEmployeeAndDateRange(employeeID, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmployeeAndDateRange", reflect.TypeOf((*MockAttendanceRepository)(nil).FindByEmployeeAndDateRange), employeeID, startDate, endDate)
}

// FindByID mocks base method.
func (m *MockAttendanceRepository) FindByID(id uint) (*entity.Attendance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*entity.Attendance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockAttendanceRepositoryMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockAttendanceRepository)(nil).FindByID), id)
}

// Update mocks base method.
func (m *MockAttendanceRepository) Update(attendance *entity.Attendance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", attendance)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAttendanceRepositoryMockRecorder) Update(attendance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAttendanceRepository)(nil).Update), attendance)
}
