// Code generated by MockGen. DO NOT EDIT.
// Source: notification_service.go
//
// Generated by this command:
//
//	mockgen -source=notification_service.go -destination=../mock/mock_notification_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNotificationService is a mock of NotificationService interface.
type MockNotificationService struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationServiceMockRecorder
	isgomock struct{}
}

// MockNotificationServiceMockRecorder is the mock recorder for MockNotificationService.
type MockNotificationServiceMockRecorder struct {
	mock *MockNotificationService
}

// NewMockNotificationService creates a new mock instance.
func NewMockNotificationService(ctrl *gomock.Controller) *MockNotificationService {
	mock := &MockNotificationService{ctrl: ctrl}
	mock.recorder = &MockNotificationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationService) EXPECT() *MockNotificationServiceMockRecorder {
	return m.recorder
}

// NotifyApprovalResult mocks base method.
func (m *MockNotificationService) NotifyApprovalResult(ctx context.Context, employeeNumber int, result, message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyApprovalResult", ctx, employeeNumber, result, message)
}

// NotifyApprovalResult indicates an expected call of NotifyApprovalResult.
func (mr *MockNotificationServiceMockRecorder) NotifyApprovalResult(ctx, employeeNumber, result, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyApprovalResult", reflect.TypeOf((*MockNotificationService)(nil).NotifyApprovalResult), ctx, employeeNumber, result, message)
}

// NotifyPendingApproval mocks base method.
func (m *MockNotificationService) NotifyPendingApproval(ctx context.Context, approverID int, requestType, requestID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotifyPendingApproval", ctx, approverID, requestType, requestID)
}

// NotifyPendingApproval indicates an expected call of NotifyPendingApproval.
func (mr *MockNotificationServiceMockRecorder) NotifyPendingApproval(ctx, approverID, requestType, requestID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyPendingApproval", reflect.TypeOf((*MockNotificationService)(nil).NotifyPendingApproval), ctx, approverID, requestType, requestID)
}
