// Code generated by MockGen. DO NOT EDIT.
// Source: attendance_correction_service.go
//
// Generated by this command:
//
//	mockgen -source=attendance_correction_service.go -destination=../mock/mock_attendance_correction_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/nanato-okajima/attendance_management/internal/entity"
	service "github.com/nanato-okajima/attendance_management/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockAttendanceCorrectionService is a mock of AttendanceCorrectionService interface.
type MockAttendanceCorrectionService struct {
	ctrl     *gomock.Controller
	recorder *MockAttendanceCorrectionServiceMockRecorder
	isgomock struct{}
}

// MockAttendanceCorrectionServiceMockRecorder is the mock recorder for MockAttendanceCorrectionService.
type MockAttendanceCorrectionServiceMockRecorder struct {
	mock *MockAttendanceCorrectionService
}

// NewMockAttendanceCorrectionService creates a new mock instance.
func NewMockAttendanceCorrectionService(ctrl *gomock.Controller) *MockAttendanceCorrectionService {
	mock := &MockAttendanceCorrectionService{ctrl: ctrl}
	mock.recorder = &MockAttendanceCorrectionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttendanceCorrectionService) EXPECT() *MockAttendanceCorrectionServiceMockRecorder {
	return m.recorder
}

// ApproveCorrectionRequest mocks base method.
func (m *MockAttendanceCorrectionService) ApproveCorrectionRequest(ctx context.Context, id uint, approverID int, comment string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApproveCorrectionRequest", ctx, id, approverID, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApproveCorrectionRequest indicates an expected call of ApproveCorrectionRequest.
func (mr *MockAttendanceCorrectionServiceMockRecorder) ApproveCorrectionRequest(ctx, id, approverID, comment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApproveCorrectionRequest", reflect.TypeOf((*MockAttendanceCorrectionService)(nil).ApproveCorrectionRequest), ctx, id, approverID, comment)
}

// CreateCorrectionRequest mocks base method.
func (m *MockAttendanceCorrectionService) CreateCorrectionRequest(ctx context.Context, req *service.CreateCorrectionRequestInput) (*entity.AttendanceCorrection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCorrectionRequest", ctx, req)
	ret0, _ := ret[0].(*entity.AttendanceCorrection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCorrectionRequest indicates an expected call of CreateCorrectionRequest.
func (mr *MockAttendanceCorrectionServiceMockRecorder) CreateCorrectionRequest(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCorrectionRequest", reflect.TypeOf((*MockAttendanceCorrectionService)(nil).CreateCorrectionRequest), ctx, req)
}

// GetCorrectionRequestByID mocks base method.
func (m *MockAttendanceCorrectionService) GetCorrectionRequestByID(ctx context.Context, id uint) (*entity.AttendanceCorrection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCorrectionRequestByID", ctx, id)
	ret0, _ := ret[0].(*entity.AttendanceCorrection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCorrectionRequestByID indicates an expected call of GetCorrectionRequestByID.
func (mr *MockAttendanceCorrectionServiceMockRecorder) GetCorrectionRequestByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCorrectionRequestByID", reflect.TypeOf((*MockAttendanceCorrectionService)(nil).GetCorrectionRequestByID), ctx, id)
}

// GetCorrectionRequests mocks base method.
func (m *MockAttendanceCorrectionService) GetCorrectionRequests(ctx context.Context, employeeNumber int, status *entity.ApprovalStatus) ([]*entity.AttendanceCorrection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCorrectionRequests", ctx, employeeNumber, status)
	ret0, _ := ret[0].([]*entity.AttendanceCorrection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCorrectionRequests indicates an expected call of GetCorrectionRequests.
func (mr *MockAttendanceCorrectionServiceMockRecorder) GetCorrectionRequests(ctx, employeeNumber, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCorrectionRequests", reflect.TypeOf((*MockAttendanceCorrectionService)(nil).GetCorrectionRequests), ctx, employeeNumber, status)
}

// RejectCorrectionRequest mocks base method.
func (m *MockAttendanceCorrectionService) RejectCorrectionRequest(ctx context.Context, id uint, approverID int, reason string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectCorrectionRequest", ctx, id, approverID, reason)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectCorrectionRequest indicates an expected call of RejectCorrectionRequest.
func (mr *MockAttendanceCorrectionServiceMockRecorder) RejectCorrectionRequest(ctx, id, approverID, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectCorrectionRequest", reflect.TypeOf((*MockAttendanceCorrectionService)(nil).RejectCorrectionRequest), ctx, id, approverID, reason)
}
