// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=../../mock/mock_leave_repository.go -package=mock -mock_names Repository=MockLeaveRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/nanato-okajima/attendance_management/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockLeaveRepository is a mock of Repository interface.
type MockLeaveRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLeaveRepositoryMockRecorder
	isgomock struct{}
}

// MockLeaveRepositoryMockRecorder is the mock recorder for MockLeaveRepository.
type MockLeaveRepositoryMockRecorder struct {
	mock *MockLeaveRepository
}

// NewMockLeaveRepository creates a new mock instance.
func NewMockLeaveRepository(ctrl *gomock.Controller) *MockLeaveRepository {
	mock := &MockLeaveRepository{ctrl: ctrl}
	mock.recorder = &MockLeaveRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeaveRepository) EXPECT() *MockLeaveRepositoryMockRecorder {
	return m.recorder
}

// CheckOverlap mocks base method.
func (m *MockLeaveRepository) CheckOverlap(ctx context.Context, employeeNumber int, startDate, endDate time.Time, excludeID *uint) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckOverlap", ctx, employeeNumber, startDate, endDate, excludeID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckOverlap indicates an expected call of CheckOverlap.
func (mr *MockLeaveRepositoryMockRecorder) CheckOverlap(ctx, employeeNumber, startDate, endDate, excludeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckOverlap", reflect.TypeOf((*MockLeaveRepository)(nil).CheckOverlap), ctx, employeeNumber, startDate, endDate, excludeID)
}

// CountApprovedDays mocks base method.
func (m *MockLeaveRepository) CountApprovedDays(ctx context.Context, employeeNumber, year int) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountApprovedDays", ctx, employeeNumber, year)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountApprovedDays indicates an expected call of CountApprovedDays.
func (mr *MockLeaveRepositoryMockRecorder) CountApprovedDays(ctx, employeeNumber, year any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountApprovedDays", reflect.TypeOf((*MockLeaveRepository)(nil).CountApprovedDays), ctx, employeeNumber, year)
}

// Create mocks base method.
func (m *MockLeaveRepository) Create(ctx context.Context, leave *entity.LeaveRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, leave)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLeaveRepositoryMockRecorder) Create(ctx, leave any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLeaveRepository)(nil).Create), ctx, leave)
}

// FindByEmployeeNumber mocks base method.
func (m *MockLeaveRepository) FindByEmployeeNumber(ctx context.Context, employeeNumber int, status *entity.ApprovalStatus) ([]*entity.LeaveRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmployeeNumber", ctx, employeeNumber, status)
	ret0, _ := ret[0].([]*entity.LeaveRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmployeeNumber indicates an expected call of FindByEmployeeNumber.
func (mr *MockLeaveRepositoryMockRecorder) FindByEmployeeNumber(ctx, employeeNumber, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmployeeNumber", reflect.TypeOf((*MockLeaveRepository)(nil).FindByEmployeeNumber), ctx, employeeNumber, status)
}

// FindByID mocks base method.
func (m *MockLeaveRepository) FindByID(ctx context.Context, id uint) (*entity.LeaveRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.LeaveRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockLeaveRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockLeaveRepository)(nil).FindByID), ctx, id)
}

// FindPendingApprovals mocks base method.
func (m *MockLeaveRepository) FindPendingApprovals(ctx context.Context) ([]*entity.LeaveRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindPendingApprovals", ctx)
	ret0, _ := ret[0].([]*entity.LeaveRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindPendingApprovals indicates an expected call of FindPendingApprovals.
func (mr *MockLeaveRepositoryMockRecorder) FindPendingApprovals(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindPendingApprovals", reflect.TypeOf((*MockLeaveRepository)(nil).FindPendingApprovals), ctx)
}

// Update mocks base method.
func (m *MockLeaveRepository) Update(ctx context.Context, leave *entity.LeaveRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, leave)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLeaveRepositoryMockRecorder) Update(ctx, leave any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLeaveRepository)(nil).Update), ctx, leave)
}
